const baseURL = "https://writersperhour.com";
// export const baseURL = "https://writersperhour.dev";
const serviceLink =[
    "/buy-persuasive-essay",
    "/ib-internal-assessment",
    "/paper-editing-service",
    "/write-my-paper",
    "/do-my-powerpoint",
    "/write-my-thesis",
    "/buy-college-papers",
    "/analysis-papers",
    "/phd-papers",
    "/buy-personal-statement",
    "/write-my-speech",
    "/buy-research-proposal",
    "/write-my-book-report",
    "/write-my-lab-report",
    "/do-my-research-paper",
    "/write-my-discussion-post-for-me",
    "/write-my-annotated-bibliography",
    "/argumentative-essay-writer",
    "/dissertation-writer",
    "/extended-essay-writer",
    "/fast-essay-writer",
    "/write-my-essay-please",
    "/homework-writers",
    "/business-plan-writers",
    "/creative-writers",
    "/mba-essay-writers",
    "/capstone-project-writers",
    "/research-paper-writers",
    "/urgent-essay-writing-service",
    "/write-my-assignment",
    "/write-my-literature-review",
    "/tok_essay",
    "/psychology-papers",
    "/do-my-coursework",
    "/biology-papers",
    "/philosophy-papers",
    "/do-my-case-study",
    "/do-my-math-problems",
    "/university-essays",
    "/write-my-scholarship-essay",
    "/buy-non-plagiarized-essay",
    "/do-my-accounting-assignment",
    "/case-brief-writing-service",
    "/marketing-plan-writing-service"
]
module.exports  = {
    baseURL,
    serviceLink,
    GUI: `${baseURL}/gui`,
    HOME: `${baseURL}/`,
    BLOG: `${baseURL}/blog`,
    BLOG_CATEGORY: `${baseURL}/blog/category`,
    BLOG_AUTHOR: `${baseURL}/blog/author`,
    HELP: `${baseURL}/help`,
    HELP_SEARCH: `${baseURL}/help/search`,
    HELP_TOPIC: `${baseURL}/help/topic`,
    ESSAY_WRITERS: `${baseURL}/essay-writers`,
    IB_WRITERS: `${baseURL}/ib-writers`,
    HOW_IT_WORKS: `${baseURL}/how-it-works`,
    PRICES_AND_DISCOUNTS: `${baseURL}/prices-and-discounts`,
    SAMPLES: `${baseURL}/samples`,
    CONTACTS: `${baseURL}/contacts`,
    ABOUT: `${baseURL}/about`,
    TESTIMONIALS: `${baseURL}/testimonials`,
    POLICY_PRIVACY: `${baseURL}/legal/privacy`,
    POLICY_REFUND: `${baseURL}/legal/refund`,
    POLICY_COOKIE: `${baseURL}/legal/cookie`,
    POLICY_REVISION: `${baseURL}/legal/revision`,
    POLICY_ACCEPTABLE: `${baseURL}/legal/acceptable`,
    TERMS_AND_CONDITIONS: `${baseURL}/legal/terms`,
    FAQ: `${baseURL}/faq`,
    ORDER: `${baseURL}/order`,
    ORDERS: `${baseURL}/orders`,
    ORDERS_ACTIVE: `${baseURL}/orders/active`,
    ORDERS_UNPAID: `${baseURL}/orders/unpaid`,
    ORDERS_COMPLETED: `${baseURL}/orders/completed`,
    ORDERS_CANCELED: `${baseURL}/orders/canceled`,
    SIGN_IN: `${baseURL}/signin`,
    SIGN_UP: `${baseURL}/signup`,
    SETTINGS: `${baseURL}/settings`,
    OUR_WRITERS: `${baseURL}/our-writers`,
    WRITE_FOR_US: `${baseURL}/write-for-us`,
    FAST_ESSAY_WRITERS: `${baseURL}/fast-essay-writer`,
    SETTINGS_AVATAR: `${baseURL}/settings/avatar`,
    SETTINGS_PROFILE: `${baseURL}/settings/profile`,
    FORGOT_PASSWORD: `${baseURL}/password/request`
};
